// <auto-generated />
using System;
using LASERISAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LASERISAPI.Migrations
{
    [DbContext(typeof(EntryDB))]
    [Migration("20250225140547_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("LASERISAPI.Models.Entry", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("itemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("manufacturerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("orderCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("physicalDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("productDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("productLink")
                        .HasColumnType("TEXT");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("serialNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("signedOutDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("signedOutTo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("signedOutToId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
