// <auto-generated />
using LASERISAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LASERISAPI.Migrations
{
    [DbContext(typeof(EntryDB))]
    partial class EntryDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LASERISAPI.Models.Entry", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("itemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("manufacturerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("orderCode")
                        .HasColumnType("TEXT");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("serialNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
